### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by LukeOnuke** [jamietech/MinecraftServerPing#10]
Due to a lack of a licence you are implying copyright to a library that we need to copy paste code from, you are literaly asking people to commit crime.

**Comment by jamietech** [comment]
There is no implication that copyright subsists in this codebase. Copyright is automatically applied to the code by the applicable law. However, there is a license on this code. The header of each file contains the [BSD-2 license](https://opensource.org/licenses/BSD-2-Clause) text. If you have any concerns about the implications of using code under this license, you should engage a lawyer.
