### ISSUE TITLE
IP address rather than Domain name?

### ISSUE THREAD

**Issue by Tythus** [jamietech/MinecraftServerPing#4]
I havn't really played with networking is there a way for it to accept an IP rather than a DNS?

**Comment by jamietech** [comment]
Have you tried providing an IP rather than a hostname?

**Comment by Tythus** [comment]
I had to change line 67 in minecraftping.java to 

socket.connect(new InetSocketAddress(InetAddress.getByName(options.getHostname()), options.getPort()), options.getTimeout());

My only other concern right now is threading it so I can check multiple IP's simultaneously.

**Comment by jamietech** [comment]
I'm pretty sure the constructor I'm using already does that call itself.

You have to deal with threading yourself. Just make a thread and call MinecraftPing.getPing() and it won't block your main thread.
