### ISSUE TITLE
[Request] Color Strip for data.getDescription()

### ISSUE THREAD

**Issue by xCykrix** [jamietech/MinecraftServerPing#5]
I was wondering if you could add a pre-set option to strip all §1-9 §a-f options in descriptions instead of the bulky amount I have to write for it each time.

~ Cykrix

**Comment by kobiluvesmemes** [comment]
Bump for this, its really annoying.

**Comment by sammyvsparks** [comment]
I could make it, but im not sure if he's even managing the project

**Comment by sammyvsparks** [comment]
Might clone and credit it

**Comment by jamietech** [comment]
I'm not sure that colour stripping is within the ambit of this project, sorry.

**Comment by sammyvsparks** [comment]
For MOTD, There are the § icons and it is very annoying and hard to fix the motd with that.

**Comment by sgdc3** [comment]
```Java
...
String motd = response.getDescription();
motd = ChatColor.translateAlternateColorCodes('§', motd);
motd = ChatColor.stripColor(motd);
...
```

**Comment by sammyvsparks** [comment]
not using this project with bukkit and my use for it is way outside the scope of color support. this project works far more than in just minecraft and removing the colors is a pain.

**Comment by sgdc3** [comment]
Yeah, but you can still look at how these method works ;) They should be available from the api sourcecode.

**Comment by sgdc3** [comment]
Just copy this class, it should be standalone: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/ChatColor.java

**Comment by sammyvsparks** [comment]
Not the point i was getting at..

**Comment by sgdc3** [comment]
```Java
public class ColorUtils {

    /**
     * The special character which prefixes all chat colour codes. Use this if
     * you need to dynamically convert colour codes from your custom format.
     */
    public static final char COLOR_CHAR = '\u00A7';
    private static final Pattern STRIP_COLOR_PATTERN = Pattern.compile("(?i)" + String.valueOf(COLOR_CHAR) + "[0-9A-FK-OR]");

    /**
     * Strips the given message of all color codes
     *
     * @param input String to strip of color
     * @return A copy of the input string, without any coloring
     */
    public static String stripColor(final String input) {
        if (input == null) {
            return null;
        }
        return STRIP_COLOR_PATTERN.matcher(input).replaceAll("");
    }
}

```

**Comment by sgdc3** [comment]
@sammyvsparks

**Comment by lucaazalim** [comment]
I know that this issue is very old but in order to help future googlers, I've added the `getStrippedText()` method to the `MinecraftPingReply.Description` class on [my fork](https://github.com/lucaazalim/minecraft-server-ping) to retrieve the stripped description text.

**Comment by xCykrix** [comment]
Nice :) - I was planning on doing that since I learned far more Java when I looked back into this
